const games = [
  {
    name: "EA Sports FC 26",
    description: "Football simulation game.",
    genre: "Sports",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Both",
    priceType: "Paid",
    publisher: "EA Sports",
    releaseYear: 2025,
    rating: 9.3,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2195250/header.jpg",
    featured: true,
  },
  {
    name: "Grand Theft Auto V",
    description: "Open world action game.",
    genre: "Action",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Both",
    priceType: "Paid",
    publisher: "Rockstar Games",
    releaseYear: 2015,
    rating: 9.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg",
    featured: true,
  },
  {
    name: "Red Dead Redemption 2",
    description: "Western action adventure.",
    genre: "Adventure",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Rockstar Games",
    releaseYear: 2018,
    rating: 9.9,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg",
    featured: true,
  },
  {
    name: "Valorant",
    description: "Competitive FPS.",
    genre: "Shooter",
    platform: ["PC"],
    mode: "Multiplayer",
    priceType: "Free",
    publisher: "Riot Games",
    releaseYear: 2020,
    rating: 9.1,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2941000/header.jpg",
    featured: true,
  },
  {
    name: "Counter-Strike 2",
    description: "Tactical FPS.",
    genre: "Shooter",
    platform: ["PC"],
    mode: "Multiplayer",
    priceType: "Free",
    publisher: "Valve",
    releaseYear: 2023,
    rating: 9.0,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg",
    featured: false,
  },
  {
    name: "Minecraft",
    description: "Sandbox survival.",
    genre: "Adventure",
    platform: ["PC", "Mobile", "PlayStation"],
    mode: "Both",
    priceType: "Paid",
    publisher: "Mojang",
    releaseYear: 2011,
    rating: 9.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1928420/header.jpg",
    featured: true,
  },
  {
    name: "Cyberpunk 2077",
    description: "Futuristic RPG.",
    genre: "RPG",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "CD Projekt",
    releaseYear: 2020,
    rating: 8.9,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg",
    featured: false,
  },
  {
    name: "Elden Ring",
    description: "Fantasy RPG.",
    genre: "RPG",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "FromSoftware",
    releaseYear: 2022,
    rating: 9.9,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg",
    featured: true,
  },
  {
    name: "Forza Horizon 5",
    description: "Open world racing.",
    genre: "Racing",
    platform: ["PC", "Xbox"],
    mode: "Both",
    priceType: "Paid",
    publisher: "Xbox Game Studios",
    releaseYear: 2021,
    rating: 9.4,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1551360/header.jpg",
    featured: true,
  },
  {
    name: "Need for Speed Heat",
    description: "Street racing.",
    genre: "Racing",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Both",
    priceType: "Paid",
    publisher: "EA",
    releaseYear: 2019,
    rating: 8.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1222680/header.jpg",
    featured: false,
  },
  {
    name: "Rocket League",
    description: "Cars playing football.",
    genre: "Sports",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Multiplayer",
    priceType: "Free",
    publisher: "Psyonix",
    releaseYear: 2015,
    rating: 9.0,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg",
    featured: true,
  },
  {
    name: "Resident Evil 4",
    description: "Survival horror.",
    genre: "Horror",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Capcom",
    releaseYear: 2023,
    rating: 9.5,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2050650/header.jpg",
    featured: true,
  },
  {
    name: "Phasmophobia",
    description: "Co-op horror.",
    genre: "Horror",
    platform: ["PC"],
    mode: "Multiplayer",
    priceType: "Paid",
    publisher: "Kinetic Games",
    releaseYear: 2020,
    rating: 8.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/739630/header.jpg",
    featured: false,
  },
  {
    name: "The Witcher 3",
    description: "Fantasy RPG.",
    genre: "RPG",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "CD Projekt",
    releaseYear: 2015,
    rating: 9.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/292030/header.jpg",
    featured: true,
  },
  {
    name: "Assassin's Creed Mirage",
    description: "Stealth action.",
    genre: "Action",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Ubisoft",
    releaseYear: 2023,
    rating: 8.7,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2023180/header.jpg",
    featured: false,
  },
  {
    name: "God of War Ragnarök",
    description: "Action adventure.",
    genre: "Action",
    platform: ["PlayStation"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Sony",
    releaseYear: 2022,
    rating: 9.8,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg",
    featured: true,
  },
  {
    name: "Marvel's Spider-Man 2",
    description: "Marvel action adventure.",
    genre: "Action",
    platform: ["PlayStation"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Sony",
    releaseYear: 2023,
    rating: 9.5,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1817070/header.jpg",
    featured: true,
  },
  {
    name: "Clair Obscur: Expedition 33",
    description: "Turn-based RPG.",
    genre: "RPG",
    platform: ["PC", "PlayStation", "Xbox"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Sandfall Interactive",
    releaseYear: 2025,
    rating: 9.6,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1903340/header.jpg",
    featured: true,
  },
  {
    name: "Black Myth: Wukong",
    description: "Action RPG.",
    genre: "Action",
    platform: ["PC", "PlayStation"],
    mode: "Single Player",
    priceType: "Paid",
    publisher: "Game Science",
    releaseYear: 2024,
    rating: 9.5,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/2358720/header.jpg",
    featured: true,
  },
  {
    name: "League of Legends",
    description: "MOBA multiplayer game.",
    genre: "MOBA",
    platform: ["PC"],
    mode: "Multiplayer",
    priceType: "Free",
    publisher: "Riot Games",
    releaseYear: 2009,
    rating: 9.2,
    image: "https://cdn.cloudflare.steamstatic.com/steam/apps/1225380/header.jpg",
    featured: false,
  },
];

module.exports = games;